### ISSUE TITLE
New worker: Raspberry Pi

### ISSUE THREAD

**Issue by csnover** [csnover/scummvm-docker#10]
As a currently supported port, it would be good to have an RPi worker.

**Comment by csnover** [comment]
https://hub.docker.com/r/sdthirlwall/raspberry-pi-cross-compiler

**Comment by wjp** [comment]
Work in progress: https://github.com/wjp/scummvm-docker/tree/raspberrypi

**Comment by wjp** [comment]
The worker now seems to be done, but the resulting binaries need testing.

**Comment by wjp** [comment]
Binary is running properly on a raspberrypi 3 model B. I'll clean this up and merge it in the next few days.

**Comment by wjp** [comment]
Merged as d4159c7dade0d5d40ed1e3e7c6c4501d06699ca0.
