### ISSUE TITLE
New worker: Dreamcast

### ISSUE THREAD

**Issue by csnover** [csnover/scummvm-docker#3]
Because reasons!

There is an existing Docker image with a cross-compiler, drylm/dc-dev, that can probably be used as a base.

**Comment by csnover** [comment]
https://github.com/DC-SWAT/DreamShell looks like it has patches for gcc 7.1.

**Comment by digitall** [comment]
I have taken a look at the docker file and this is intended for KOS, not libronin which ScummVM uses:
http://gamedev.allusion.net/softprj/kos/
http://dcevolution.sourceforge.net/index.php?id=libronin
https://bitbucket.org/ihi/libronin

I worked on improving and documenting the DC toolchain so we could update the existing buildbot and libraries for this last year and I have scripts and patches for this to build a repeatable toolchain. You should be able to port these into the docker framework. Will supply these by e-mail on request.

**Comment by csnover** [comment]
@digitall Please go ahead and email me or attach files here.

**Comment by csnover** [comment]
2cc973693a28b2f34ac556ee71d822e7581ed44a
